language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --exclude-group integration

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
